# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, null=True, verbose_name='Link code for deck')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Deck name')),
            ],
        ),
        migrations.CreateModel(
            name='DecksContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deck_with_word', to='back.Decks', verbose_name='Deck, containing the word')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(max_length=255, unique=True, verbose_name='English word')),
                ('rus_word', models.CharField(max_length=255, verbose_name='Russian word')),
            ],
        ),
        migrations.AddField(
            model_name='deckscontent',
            name='word',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='word_in_deck', to='back.Words', verbose_name='Single word in deck'),
        ),
    ]
